import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // Sidebar automático (recomendado)
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // O sidebar manual (descomenta y personaliza):
  /*
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Cloudflare',
      items: [
        'cloudflare/tunnels',
        'cloudflare/dns',
      ],
    },
    {
      type: 'category',
      label: 'Linux',
      items: [
        'linux/ubuntu',
        'linux/arch',
      ],
    },
  ],
  */
};

export default sidebars;
